CREATE TABLE IF NOT EXISTS hotel (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id           BIGINT,
    name               TEXT,
    chain_id           BIGINT,
    stars              INTEGER,
    rating             DOUBLE PRECISION,
    hero_photo         TEXT,
    lat                DOUBLE PRECISION,
    lng                DOUBLE PRECISION,
    contact            OID,
    checkin_policy     OID,
    address            OID,
    child_allowed      BOOLEAN,
    pets_allowed       BOOLEAN
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_hotel__hotel_id ON hotel (hotel_id);

CREATE TABLE IF NOT EXISTS hotel_i18n (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id               BIGINT      NOT NULL,
    lang                   VARCHAR(2)  NOT NULL,
    parking                TEXT,
    important_info         TEXT,
    markdown_description   OID,
    facilities             OID,
    rooms                  OID,
    hotel_type             TEXT,
    description_short      OID,
    policies               OID,
    photos                 OID,
    CONSTRAINT hotel_lang UNIQUE (hotel_id, lang),
    CONSTRAINT fk_hotel_i18n__hotel
        FOREIGN KEY (hotel_id) REFERENCES hotel(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS review (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id   BIGINT      NOT NULL,
    hotel_id    BIGINT      NOT NULL,
    external_hotel_id BIGINT NOT NULL,
    country     TEXT,
    type        TEXT,
    name        TEXT,
    avg_score   DOUBLE PRECISION,
    headline    TEXT,
    pros        OID,
    cons        OID,
    language    TEXT,
    source      TEXT,
    date        TIMESTAMP,
    CONSTRAINT fk_review__hotel
        FOREIGN KEY (hotel_id) REFERENCES hotel(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_review__hotel_review ON review (hotel_id, review_id);

CREATE INDEX IF NOT EXISTS idx_hotel_i18n_hotel ON hotel_i18n (hotel_id);
CREATE INDEX IF NOT EXISTS idx_hotel_i18n_lang  ON hotel_i18n (lang);
CREATE INDEX IF NOT EXISTS idx_review_hotel     ON review (hotel_id);
CREATE INDEX IF NOT EXISTS idx_review_lang      ON review (language);
CREATE INDEX IF NOT EXISTS idx_review_date      ON review (date);
