apiVersion: apps/v1
kind: Deployment
metadata:
  name: cupid-sync-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cupid-sync-app
  template:
    metadata:
      labels:
        app: cupid-sync-app
    spec:
      containers:
        - name: cupid-sync-app
          image: fayzsabir/cupid-sync-app:1.1.0
          ports:
            - containerPort: 8089
          envFrom:
            - configMapRef:
                name: cupid-sync-config
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8089
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8089
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: cupid-sync-app
spec:
  type: LoadBalancer
  selector:
    app: cupid-sync-app
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
