---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: kubernetes-dashboard
data:
  loki-config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
      grpc_listen_port: 9096
    common:
      instance_addr: 127.0.0.1
      path_prefix: /loki
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: memberlist
    memberlist:
      join_members: []
    schema_config:
      configs:
        - from: 2024-01-01
          store: boltdb-shipper
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h
    storage_config:
      filesystem:
        directory: /loki
      boltdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/boltdb-cache
        shared_store: filesystem
    ruler:
      rule_path: /loki/rules
      alertmanager_url: http://localhost:9093
      enable_api: true
    limits_config:
      allow_structured_metadata: true
      ingestion_rate_mb: 8
      ingestion_burst_size_mb: 16
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: kubernetes-dashboard
spec:
  serviceName: loki
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.9.8
          args:
            - -config.file=/etc/loki/loki-config.yaml
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: data
              mountPath: /loki
      volumes:
        - name: config
          configMap:
            name: loki-config
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: kubernetes-dashboard
spec:
  selector:
    app: loki
  ports:
    - port: 3100
      targetPort: 3100
